"use client";

import React from 'react';
import { Button } from '@/components/shadcn/ui/button';
import { Input } from '@/components/shadcn/ui/input';
import { Label } from '@/components/shadcn/ui/label';
import { Textarea } from '@/components/shadcn/ui/textarea';
import { Switch } from '@/components/shadcn/ui/switch';
import { useForm } from '@tanstack/react-form';
import { Loader2 } from 'lucide-react';

const styles = {
  form: `space-y-4`.trim(),
  fieldContainer: `space-y-2`.trim(),
  errorText: `text-sm text-destructive`.trim(),
  hintText: `text-xs text-muted-foreground`.trim(),
  switchContainer: `flex items-center justify-between`.trim(),
  switchLabelContainer: `space-y-0.5`.trim(),
  actionsContainer: `flex justify-end gap-2 pt-4`.trim(),
};

interface GalleryFormData {
  title: string;
  slug: string;
  description: string;
  tags: string;
  isPublic: boolean;
}

interface GalleryFormProps {
  mode: 'create' | 'edit';
  initialData?: Partial<GalleryFormData>;
  onSubmit: (data: GalleryFormData) => Promise<void>;
  onCancel?: () => void;
  isSubmitting?: boolean;
}

export function GalleryForm({ mode, initialData, onSubmit, onCancel, isSubmitting = false }: GalleryFormProps) {
  const form = useForm({
    defaultValues: {
      title: initialData?.title || '',
      slug: initialData?.slug || '',
      description: initialData?.description || '',
      tags: initialData?.tags || '',
      isPublic: initialData?.isPublic ?? true,
    },
    onSubmit: async ({ value }) => {
      await onSubmit(value as GalleryFormData);
    },
  });

  // 自动生成 slug
  const handleTitleChange = (title: string) => {
    form.setFieldValue('title', title);
    
    // 如果 slug 为空或者是自动生成的，则自动更新
    const currentSlug = form.getFieldValue('slug');
    const currentTitle = form.getFieldValue('title');
    const autoGeneratedSlug = currentTitle.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    
    if (!currentSlug || currentSlug === autoGeneratedSlug) {
      const newSlug = title.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
      form.setFieldValue('slug', newSlug);
    }
  };

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        e.stopPropagation();
        void form.handleSubmit();
      }}
      className={styles.form}
    >
      <form.Field
        name="title"
        validators={{
          onBlur: ({ value }) => {
            if (!value?.trim()) {
              return '标题不能为空';
            }
            if (value.length > 200) {
              return '标题不能超过200个字符';
            }
            return undefined;
          }
        }}
        children={(field) => (
          <div className={styles.fieldContainer}>
            <Label htmlFor="title">标题 *</Label>
            <Input
              id="title"
              value={field.state.value}
              onChange={(e) => handleTitleChange(e.target.value)}
              onBlur={field.handleBlur}
              placeholder="例如：产品图库"
              disabled={isSubmitting}
              required
            />
            {field.state.meta.errors.length > 0 && (
              <p className={styles.errorText}>{field.state.meta.errors[0]}</p>
            )}
          </div>
        )}
      />

      <form.Field
        name="slug"
        validators={{
          onBlur: ({ value }) => {
            if (!value?.trim()) {
              return 'Slug 不能为空';
            }
            if (!/^[a-z0-9-]+$/.test(value)) {
              return 'Slug 只能包含小写字母、数字和连字符';
            }
            return undefined;
          }
        }}
        children={(field) => (
          <div className={styles.fieldContainer}>
            <Label htmlFor="slug">Slug *</Label>
            <Input
              id="slug"
              value={field.state.value}
              onChange={(e) => field.handleChange(e.target.value)}
              onBlur={field.handleBlur}
              placeholder="例如：product-gallery"
              pattern="[a-z0-9-]+"
              disabled={isSubmitting}
              required
            />
            <p className={styles.hintText}>
              只能包含小写字母、数字和连字符
            </p>
            {field.state.meta.errors.length > 0 && (
              <p className={styles.errorText}>{field.state.meta.errors[0]}</p>
            )}
          </div>
        )}
      />

      <form.Field
        name="description"
        children={(field) => (
          <div className={styles.fieldContainer}>
            <Label htmlFor="description">描述</Label>
            <Textarea
              id="description"
              value={field.state.value}
              onChange={(e) => field.handleChange(e.target.value)}
              placeholder="简短描述这个图库..."
              disabled={isSubmitting}
              rows={3}
            />
          </div>
        )}
      />

      <form.Field
        name="tags"
        children={(field) => (
          <div className={styles.fieldContainer}>
            <Label htmlFor="tags">标签</Label>
            <Input
              id="tags"
              value={field.state.value}
              onChange={(e) => field.handleChange(e.target.value)}
              placeholder="React, TypeScript, 前端 (逗号分隔)"
              disabled={isSubmitting}
            />
            <p className={styles.hintText}>
              使用逗号分隔多个标签
            </p>
          </div>
        )}
      />

      <form.Field
        name="isPublic"
        children={(field) => (
          <div className={styles.switchContainer}>
            <div className={styles.switchLabelContainer}>
              <Label htmlFor="isPublic">公开状态</Label>
              <p className={styles.hintText}>
                公开后其他用户可以查看此图库
              </p>
            </div>
            <Switch
              id="isPublic"
              checked={field.state.value}
              onCheckedChange={(checked) => field.handleChange(checked)}
              disabled={isSubmitting}
            />
          </div>
        )}
      />

      <div className={styles.actionsContainer}>
        {onCancel && (
          <Button
            type="button"
            variant="outline"
            onClick={onCancel}
            disabled={isSubmitting}
          >
            取消
          </Button>
        )}
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
          {mode === 'create' ? '创建' : '保存'}
        </Button>
      </div>
    </form>
  );
}
